### ISSUE TITLE
Feature request: support temporary AWS credentials

### ISSUE THREAD

**Issue by RomanHotsiy** [BohdanPetryshyn/basti#11]
Some of our accounts use SSO to login into AWS. Would be great if basti can support this flow.

This should be possible with a [`aws sso login`](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-sso.html) command.

**Comment by RomanHotsiy** [comment]
How would you implement it in terms of UX?

My idea was to add a new flag to CLI commands `--login-sso <profile-name>` which when used will start SSO session before anything else.

What do you think?

**Comment by BohdanPetryshyn** [comment]
We could try wrapping the AWS CLI SSO functionality with Basti, but it isn't a trivial task. Instead, we could leave credentials management outside of Basti's area of responsibility and continue using existing credentials from the user's environment. 

The user can set up his or her environment separately using the `aws sso login` command. So it will be entirely up to the user, what credentials to use:

1. AWS CLI default or named profile
2. `AWS_KEY_ID` and `AWS_SECRET_KEY` environment variables
3. Temporary credentials obtained using `aws sso login`

**Comment by RomanHotsiy** [comment]
Okay, let me try to set up sso in our org to see how it works and how difficult it would be to use.

I would vote for wrapping it into the basti though to make end-users UX better.

I believe it may be used by different audience, e.g. I would like our support team to use it and they may not be as technical.

Up to you to decide though 😄

**Comment by BohdanPetryshyn** [comment]
I've just quickly set up SSO on my personal account. Here're the steps users will have to take to set up their environment with SSO credentials:

1. Install AWS CLI
2. Run `aws configure sso [--profile <profile-name>]` and enter couple of configuration values:
   
   <img width="526" alt="image" src="https://user-images.githubusercontent.com/45905756/205340975-2b59144a-6589-4c6c-8803-41eaa34a7e56.png">

3. Use Basti: `[AWS_PROFILE=profile-name] basti connect`
4. In case temporary credentials expire, refresh them with `aws sso login`

The profile-related options wrapped in square brackets (`[]`) are entirely optional if the user doesn't want to maintain multiple profiles on his machine.

**Comment by RomanHotsiy** [comment]
Gotcha. Then it's not too bad 👍

**Comment by BohdanPetryshyn** [comment]
Please, share your experience after establishing SSO and Basti for your organization!

**Comment by RomanHotsiy** [comment]
This seems fine. I don't think we need anything special if you implement https://github.com/BohdanPetryshyn/basti/issues/12
