### ISSUE TITLE
session-manager-plugin installation doesn't work with npx on Arm64

### ISSUE THREAD

**Issue by BohdanPetryshyn** [BohdanPetryshyn/basti#20]
It was reported that `session-manager-plugin` was not installed automatically when using `basti` with `npx`. 

Platform: MacOS
Arch: Arm64

**Comment by BohdanPetryshyn** [comment]
First, the issue has to be reproduced

**Comment by BohdanPetryshyn** [comment]
The issue was reproduced and fixed with https://github.com/BohdanPetryshyn/basti/commit/3e175fb0581e8381370ffc04f065d15f49ac9de3

**Comment by motnyk** [comment]
Works like a charm! 🚀 ❤️
