### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by adamaltman** [BohdanPetryshyn/basti#23]
If they aren't yet, logs should be sent to cloudwatch (this should include system logs and access logs).

Why? An audit trail is vital for security programs, so to use this in a production environment, logging needs to be enabled.

If logs are already enabled, then logs should be mentioned in the README.

**Comment by BohdanPetryshyn** [comment]
Sessions Manager, which Basti uses to establish a port forwarding session, persists session history by default. [This article](https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager-working-with-view-history.html) in AWS docs shows how to access them.

We have to include this in the Basti documentation.

**Comment by BohdanPetryshyn** [comment]
As now [described in README](https://github.com/BohdanPetryshyn/basti#usage-audit), AWS CloudTrail could be used to audit Basti usage with more details than AWS Session Manager history.
