### ISSUE TITLE
Secure server hardening

### ISSUE THREAD

**Issue by adamaltman** [BohdanPetryshyn/basti#24]
Basti init starts an EC2 instance. Then it is in the VPC for potentially a long time (even though "off" when not in use). However, how does the instance get security patches? How is the instance monitored for security purposes? This type of documentation should be in the README so that a CISO can easily review to determine if Basti will work in their organization. Also, they would probably want to know the base image (assuming it is using a public one maintained by AWS or similar organization).

Side note: could basti work with fargate too instead of ec2?

**Comment by BohdanPetryshyn** [comment]
The reason Basti uses EC2 instead of Fargate is that Session Manager port forwarding is only supported for EC2

**Comment by BohdanPetryshyn** [comment]
I have two solutions in mind for keeping the instance up-to-date:

1. Adding a command like `basti patch` that would apply all the patches according to some policy.
2. Setting up an AWS Patch Manager rule that would do this automatically. The problem with this approach is that it (most likely) doesn't work when the instance is stopped.
3. Two solutions could be combined so that the command would start the instance and patch it with Patch Manager.

**Comment by BohdanPetryshyn** [comment]
What about the image (AMI) used for the EC2 instance - Basti uses the latest Amazon Linux 2 kernel version 5.10 available at `basti init` time.

**Comment by BohdanPetryshyn** [comment]
The reason Basti uses EC2 instead of Fargate is that Session Manager port forwarding is only supported for EC2.

**Comment by adamaltman** [comment]
Noting some of this in documentation would be good. I vote to prioritize `basti patch` so that it can be viable for production use. Also, is there a `basti destroy` or some way to kill the EC2 instance?

**Comment by BohdanPetryshyn** [comment]
`basti cleanup` command destroys all the resources created by Basti: 

https://github.com/BohdanPetryshyn/basti#cleanup-optional

**Comment by BohdanPetryshyn** [comment]
@adamaltman, Basti now updates software packages and OS kernel at shutdown time once a day as described in README [here](https://github.com/BohdanPetryshyn/basti#software) 😉

**Comment by BohdanPetryshyn** [comment]
The new security feature is available in [v1.1.0](https://github.com/BohdanPetryshyn/basti/releases/tag/v1.1.0)
