### ISSUE TITLE
Describe required AWS permissions in README

### ISSUE THREAD

**Issue by dennislapchenko** [BohdanPetryshyn/basti#25]
Tested the tool, very impressed by the smoothness of setup and functionality.
One thing, however, which would have to be figured out, if an org wants to give this functionality to devs: is to what set of permissions to grant. Could you please describe this in documentation?

**Comment by BohdanPetryshyn** [comment]
Hi @dennislapchenko, thank you for your feedback! 

I assume you closed your issue in favor of https://github.com/BohdanPetryshyn/basti/issues/17? Now that multiple users asked for this, I'll add a section soon!
