### ISSUE TITLE
Support Node < 14.0.0

### ISSUE THREAD

**Issue by BohdanPetryshyn** [BohdanPetryshyn/basti#29]
#### Problem
Using `basti` with Node versions lower than 14.0.0 results in errors connected to [Subpath Imports](https://nodejs.org/api/packages.html#subpath-imports) and ESModules usage. 

#### Proposed solution
The build process has to be reconfigured to support older Node versions.

#### References
Related issue: https://github.com/BohdanPetryshyn/basti/issues/21

**Comment by adamaltman** [comment]
https://nodejs.dev/en/about/releases/ I wouldn't add support for less than node 14 in any new product. Especially one that has security implications.

**Comment by BohdanPetryshyn** [comment]
Thank you for pointing this out, @adamaltman! Completely makes sense to me, especially considering the v14 EOL is less than a week from now 😄
