### ISSUE TITLE
Improve error messages structure

### ISSUE THREAD

**Issue by AyeOne** [BohdanPetryshyn/basti#46]
## Feature Description

Improve error messages structure, as it makes it easier to solve a problem for end-user.
For example:
```
❌ Error checking target state. Unexpected error: The SSO session associated with this profile has expired. To refresh this SSO session run aws sso login with the corresponding profile.
```

Can be
```
❌ Error checking target state. 

⚠️ The SSO session associated with this profile has expired. 

To refresh the SSO session, please run the following command with the corresponding profile:

aws sso login --profile <profile_name>

```
## Proposed Solution

Separate error message from suggested fix, when it's possible

## Related Issues/PRs
not yet : )

**Comment by BohdanPetryshyn** [comment]
I'm sorry, but I'm closing this issue to clean up a bit. The existing error message provides enough information for the user to solve the problem. It literally tells the solution 🙂

> To refresh this SSO session run aws sso login with the corresponding profile.
