### ISSUE TITLE
Add custom tags to instance and related resources

### ISSUE THREAD

**Issue by DrFunk-n-stein** [BohdanPetryshyn/basti#50]
## Feature Description

Add possibility to add custom tags that are applied to the instance and related resources. 

## Use Case

If an organization has a tag policy / SCP combination active that enforces a set of standard tags, basti cannot be used. 
Additionally, some organizations have cost allocation tags active which makes it easier to accumulate cost that are induced by basti. 
Also, ownership tags are a use case that could come in handy if teams are using basti to access their resources for increased transparency.

## Proposed Solution

- add key-value list of tags, maybe in the basti config or as json for the cli that are applied to the basti instance on creation

## Related Issues/PRs

none

**Comment by BohdanPetryshyn** [comment]
@DrFunk-n-stein sounds like a really valuable enhancement! Currently, the only option is to set the tags manually after setting up the bastion instance with `basti init`. This is actually the solution we use at my current company.

This feature will be added to Basti CLI when the turn comes according to the current priorities.

Meanwhile, I'd like to ask you if you're using any infrastructure-as-code solution. Basti setup using CDK construct will be introduced very soon (#48). The Basti Terraform module will come next.

**Comment by DrFunk-n-stein** [comment]
The solution you mentioned with manual applying of tags won't work in any setup that enforces tags via Service Control Policies+Tagging Policies, that's why I mentioned it explicitely. 
And... you know lazy devs: many of them will simply forget adding tags (I'm thinking of setups at scale with several teams and different knowledge levels), so you could end up with a zoo of stopped bastion hosts that accumulate cost (-> e.g. EBS volumes).

**Comment by BohdanPetryshyn** [comment]
To be honest, I have never used SCPs or Tagging Policies before. Does this mean that you cannot run `basti init` at all because resources without specific tags cannot be created? If that is the case, the feature seems to be of high priority, and I will try to implement a solution ASAP. Providing the tags to the basti init command as a JSON file appears to be the best minimal valuable solution here.

**Comment by DrFunk-n-stein** [comment]
@BohdanPetryshyn yes, that is the case. The AWS API will simply deny e.g. `ec2:RunInstances` operations or similar (depending on the SCP)

**Comment by BohdanPetryshyn** [comment]
We need to add tags configuration to both interactive mode and CLI arguments. 

In the interactive mode, we need to introduce an optional "Advanced configuration" step, where the user will input custom tags one by one. 

For the CLI arguments, we can add a `--tags` argument that will accept values `aws ec2 create-tags` command accepts ([docs](https://docs.aws.amazon.com/cli/latest/reference/ec2/create-tags.html)).

I think using the same tags for all the resources created by Basti should be enough for the first implementation. We can add the ability to set separate tags for each resource later if needed.

@DrFunk-n-stein what do you think?

**Comment by DrFunk-n-stein** [comment]
@BohdanPetryshyn it's rather uncommon to set different set of tag-keys for resources that belong together.
Adding this is super optional in my eyes.

**Comment by DrFunk-n-stein** [comment]
As this will be moving to cdk or terraform anyways, we could use stack-tags (CF/CDK) or default tags (tf, aws provider) to male this easier and consistent

**Comment by BohdanPetryshyn** [comment]
Thank you, @bobveringa!

**Comment by BohdanPetryshyn** [comment]
Hey @DrFunk-n-stein 👋 

Custom tags support was introduced in `v1.4.0`. I'd really love to know if this helps in the situations you described above!
