### ISSUE TITLE
Please specify a preferred security contact

### ISSUE THREAD

**Issue by ramimac** [BohdanPetryshyn/basti#73]
## Bug Description

Hello,

I'd like to reach out privately with a potential (minor) security issue / recommendation. Would you mind sharing a preferred contact method or [enabling private vulnerability reporting](https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability#about-privately-reporting-a-security-vulnerability)?

Thank you!

**Comment by BohdanPetryshyn** [comment]
Hello, @ramimac 👋 

Thank you for reaching out! I enabled private vulnerability reporting so you can now submit your find.

**Comment by BohdanPetryshyn** [comment]
I will keep this issue open until I set up SECURITY.md
